// <auto-generated />
using System;
using Final_Insure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Insure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725062108_OfficerRemarksColumn")]
    partial class OfficerRemarksColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_Insure.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<bool>("AccidentMatchesDescription")
                        .HasColumnType("bit");

                    b.Property<decimal>("AssessedAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssessmentRemarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("EvidencePhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GarageDetails")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SurveyorId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("SurveyorId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Final_Insure.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("AccidentAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfficerRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClaimId");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Final_Insure.Models.ClaimDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments");
                });

            modelBuilder.Entity("Final_Insure.Models.FraudCheck", b =>
                {
                    b.Property<int>("FraudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FraudId"));

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplianceOfficerId")
                        .HasColumnType("int");

                    b.Property<int>("FraudScore")
                        .HasColumnType("int");

                    b.Property<string>("InvestigatorRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFraudulent")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskFlag")
                        .HasColumnType("int");

                    b.HasKey("FraudId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ComplianceOfficerId");

                    b.ToTable("FraudChecks");
                });

            modelBuilder.Entity("Final_Insure.Models.InsurancePlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.ToTable("InsurancePlans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            BasePremium = 7200m,
                            CoverageAmount = 800000m,
                            Description = "Covers damage to others (Third-Party liability only). Required by law.",
                            IsActive = true,
                            PlanName = "Third-Party Mandatory",
                            PlanType = "Vehicle"
                        },
                        new
                        {
                            PlanId = 2,
                            BasePremium = 18500m,
                            CoverageAmount = 2500000m,
                            Description = "Covers damage to your car + others (Natural disasters, theft, accidents).",
                            IsActive = true,
                            PlanName = "Comprehensive Car Insurance",
                            PlanType = "Vehicle"
                        });
                });

            modelBuilder.Entity("Final_Insure.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("ChassisNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleRC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Final_Insure.Models.SettlementLog", b =>
                {
                    b.Property<int>("SettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettlementId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("SettlementAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("SettlementStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SettlementId");

                    b.HasIndex("ClaimId");

                    b.ToTable("SettlementLogs");
                });

            modelBuilder.Entity("Final_Insure.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Final_Insure.Models.Assessment", b =>
                {
                    b.HasOne("Final_Insure.Models.Claim", "Claim")
                        .WithMany("Assessments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Insure.Models.User", "Surveyor")
                        .WithMany("Assessments")
                        .HasForeignKey("SurveyorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Surveyor");
                });

            modelBuilder.Entity("Final_Insure.Models.Claim", b =>
                {
                    b.HasOne("Final_Insure.Models.User", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Final_Insure.Models.User", "Customer")
                        .WithMany("Claims")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Final_Insure.Models.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedOfficer");

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Final_Insure.Models.ClaimDocument", b =>
                {
                    b.HasOne("Final_Insure.Models.Claim", "Claim")
                        .WithMany("ClaimDocuments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Final_Insure.Models.FraudCheck", b =>
                {
                    b.HasOne("Final_Insure.Models.Claim", "Claim")
                        .WithMany("FraudChecks")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Insure.Models.User", "ComplianceOfficer")
                        .WithMany()
                        .HasForeignKey("ComplianceOfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Claim");

                    b.Navigation("ComplianceOfficer");
                });

            modelBuilder.Entity("Final_Insure.Models.Policy", b =>
                {
                    b.HasOne("Final_Insure.Models.User", "Customer")
                        .WithMany("Policies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Final_Insure.Models.SettlementLog", b =>
                {
                    b.HasOne("Final_Insure.Models.Claim", "Claim")
                        .WithMany("SettlementLogs")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Final_Insure.Models.Claim", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("ClaimDocuments");

                    b.Navigation("FraudChecks");

                    b.Navigation("SettlementLogs");
                });

            modelBuilder.Entity("Final_Insure.Models.Policy", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Final_Insure.Models.User", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Claims");

                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
